SKILLS = [
  "Communication skills",
  "Interpersonal skills",
  "Problem-solving skills",
  "Adaptability",
  "Time management",
  "Organization",
  "Leadership",
  "Attention to detail",
  "Creativity",
  "Positive attitude",
  "Emotional intelligence",
  "Teamwork",
  "Conflict resolution",
  "Active listening",
  "Customer service orientation",
  "Positive impact",
  "Flexibility",
  "Initiative",
  "Critical thinking",
  "Stress management",
  "Presentation skills",
  "Decision making",
  "Mentorship",
  "Negotiation skills",
  "Self-motivation",
  "Dependability",
  "Work ethic",
  "Patience",
  "Effective prioritization",
  "Good judgment",
  "Professionalism",
  "Empathy",
  "Cultural competence",
  "Collaboration",
  "Effective feedback",
  "Responsibility",
  "Goal-oriented mindset",
  "Strong work ethic",
  "Continuous learning",
  "Effective delegation",
  "Technology",
  "Entrepreneurship",
  "Finance",
  "Marketing",
  "Art",
  "Design",
  "Photography",
  "Music",
  "Writing",
  "Sports",
  "Travel",
  "Food",
  "Fashion",
  "Environmental issues",
  "Health and wellness",
  "Volunteer work",
  "Personal development",
  "Social media",
  "Politics",
  "History",
  "Languages",
  "Gaming",
  "Film and television",
  "Nature and outdoor activities",
  "Architecture",
  "Automotive",
  "Real estate",
  "Education",
  "Cooking",
  "Pets",
  "Personal finance",
  "DIY and home improvement",
  "Gardening",
  "Personal fitness",
  "Crafts",
  "Green energy",
  "Event planning",
  "Travel planning",
]